name: pos2
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0" 
  # ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^1.0.0
  # ^0.3.0
  # flutter:
  #   sdk: flutter
  sqflite_common_ffi: 2.2.5
  sqflite_common_ffi_web: ^0.3.6
  sqflite: ^2.3.0
  # sqflite_common_ffi_web: ^0.3.6
  # sqflite: ^2.2.8+4

dev_dependencies:
  # build_runner: ^2.4.0
  # build_web_compilers: ^4.0.4
  mocktail: ^1.0.0
  # ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  # ^4.0.0
